---
title: "Tablero-Distritos"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny 
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}
library(dplyr)
library(sf)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
library(shiny)
```

```{r letura de datos}
cantones <- 
  st_read(dsn = "distritos_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r lista-provincias}
# Lista ordenada de provincias + "Todas"
lista_provincias <- unique(cantones$provincia)
lista_provincias <- sort(lista_provincias)
lista_provincias <- c("Todas", lista_provincias)
```

```{r lista-cantones}
# Lista ordenada de provincias + "Todas"
lista_cantones <- unique(cantones$provincia)
lista_cantones <- sort(lista_cantones)
lista_cantones <- c("Todas", lista_cantones)
```
Column {.sidebar}
-------------------------------------

```{r filtros}
# Selector de provincia
selectInput(
  inputId = "provincia",
  label = "Provincia",
  choices = lista_provincias,
  selected = "Todos"
)
# Función para filtrar los datos con base en los controles de entrada
filtrarCantones <- reactive({
  # Valor inicial del objeto que va a retornarse
  cantones_filtrados <- cantones
  
  # Filtrado de cantones por provincia
  if (input$provincia != "Todas") {
    cantones_filtrados <-
      cantones_filtrados %>%
      filter(provincia == input$provincia)
  }
  
  return(cantones_filtrados)
})



selectInput(
  inputId = "cantones",
  label = "cantones",
  choices = lista_cantones,
  selected = "todos"
)

filtrarCantones <- reactive({
  cantones_filtrados <- cantones
  if(input$canton != "Todas") {
    cantones_filtrados<-
      cantones_filtrados %>%
      filter(provincia == input$canton)
  }
  return(provincias_filtrados)
})
```

Row {data-height=10}
-----------------------------------------------------------------------

### **Fuente de los datos: [Instituto Geográfico Nacional (IGN)](http://geos.snitcr.go.cr/be/IGN_5/wfs)**

Row {data-height=590}
-----------------------------------------------------------------------

### Mapa

```{r}
# Mapa
renderLeaflet({
  # cantones <- filtrarCantones()

  leaflet() %>%
    setView(lng = -84.19452,
            lat = 9.572735,
            zoom = 7) %>%
    addTiles(group = "OpenStreetMap") %>%
    addPolygons(
      data = cantones,
      color = "black",
      opacity = 0.2,
      weight = 1.5,
      popup = paste(
        paste("<a>Cantón:</a>", cantones$canton),
        paste("<a>Área:</a>", cantones$area, "km2"),
        sep = "<br>"
      ),
      group = "Cantones"
    ) %>%
    addLayersControl(baseGroups = c("OpenStreetMap"),
                     overlayGroups = c("Cantones"))
})
```

### Tabla

```{r tabla}
# Tabla
renderDT({
  cantones <- filtrarCantones()
  
  cantones %>%
    st_drop_geometry() %>%
    select(provincia, canton, area) %>%
    arrange(desc(area)) %>%
    datatable(
      colnames = c("Provincia", "Cantón", "Área"),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )
})
```

Row {data-height=400}
-----------------------------------------------------------------------

### Gráfico de cantones con mayor área

```{r grafico}
# Gráfico
renderPlotly({
  cantones <- filtrarCantones()
  
  grafico_ggplot2 <-
    cantones %>%
    st_drop_geometry() %>%
    slice_max(area, n = 20) %>%
    ggplot(aes(x = reorder(canton,-area), y = area)) +
    geom_bar(stat = "identity") +
    xlab("Cantón") +
    ylab("Área (km2)")
  
  ggplotly(grafico_ggplot2)
})
```





